### ISSUE TITLE
Publish version with Typescript typings

### ISSUE THREAD

**Issue by Retsam** [doapp-ryanp/dynamodb-local#16]
It looks like TS typings have been added to the repository, but I don't think it's been published since then: installing 0.0.18 still doesn't include any typings.

Thanks, this package seems really helpful!

**Comment by doapp-ryanp** [comment]
Thanks - just did `npm publish` to v0.0.19.  See https://github.com/doapp-ryanp/dynamodb-local/releases/tag/v0.0.19
