### ISSUE TITLE
Error: Could not find or load main class 

### ISSUE THREAD

**Issue by ceilfors** [doapp-ryanp/dynamodb-local#32]
I got this problem when upgrading from 0.0.26 to 0.0.27/0.0.28: https://github.com/laconiajs/laconia/pull/46:

```
Error: Could not find or load main class 
```

Downgrading to 0.0.26 works. Are there any code change that I need to do for the upgrade? I can't find any release notes for 0.0.27 or 0.0.28.

**Comment by rynop** [comment]
Here's `0.0.27`: https://github.com/rynop/dynamodb-local/pull/29

Here's `0.0.28`: https://github.com/rynop/dynamodb-local/pull/31/files

I can't think of a reason either of those changes would cause your err. Unfortunately I don't have the bandwidth ATM to investigate.

**Comment by armonge** [comment]
@rynop i have the same issue, not sure what's causing it but after tinkering a bit with the code seems like adding  `shell: true` to the `spawn` options fixes it for me

**Comment by armonge** [comment]
Actually, seems the whole issue stems from passing an empty `javaOpts` argument, if i remove it then it works as expected, sent a pulll request with the fix

**Comment by rynop** [comment]
thx - 0.0.29 published
