### ISSUE TITLE
Move q from devDependency to dependency

### ISSUE THREAD

**Issue by gnestor** [doapp-ryanp/dynamodb-local#4]
`npm install dynamodb-local` doesn't install the package's devDependencies, therefore q is not installed and using dynamodb-local results in: `Error: Cannot find module 'q'`. If you move q to the package's dependencies this will fix the issue.

**Comment by doapp-ryanp** [comment]
crap yea, my b. will fix now

**Comment by doapp-ryanp** [comment]
fixed in https://github.com/doapp-ryanp/dynamodb-local/commit/cb383763b5d28be2e7f20ed4919130be9afeef5e

**Comment by doapp-ryanp** [comment]
make sure to use v0.0.9..

**Comment by gnestor** [comment]
0.0.9 is missing tar and mkdirp dependencies!

**Comment by doapp-ryanp** [comment]
sorry moving too fast. fixed in 0.0.10..

**Comment by gnestor** [comment]
Working now! Thanks.
