### ISSUE TITLE
launch() fails on Linux

### ISSUE THREAD

**Issue by charleswhchan** [doapp-ryanp/dynamodb-local#5]
OS: Linux Mint 17

Code:

```
var DynamoDbLocal = require('dynamodb-local');
DynamoDbLocal.launch(dynamoLocalPort, null, ['-sharedDb']); 
```

Result:

```
Checking for  /tmpdynamodb-local
DyanmoDb Local not installed. Installing...
## aborted
```

I think there might be a problem with in the following [code](https://github.com/doapp-ryanp/dynamodb-local/blob/master/index.js#L15):

```
var tmpDynamoLocalDirDest = os.tmpdir() + 'dynamodb-local'
```

Since os.tmp() returns `/tmp`, `tmpDyamoLocalDirDest` becomes `/tmpdynamodb-local` instead of `/tmp/dynamodb-local`.

Seems like an easy fix for Linux, but I don't know the impact on other OSes.

**Comment by charleswhchan** [comment]
I should also mentioned that I tried to created the `/tmpdynamodb-local` directory manually and re-ran the node script. However it still end up aborting without any indication of what the error is and the `/tmpdynamodb-local` directory is empty as well.

**Comment by doapp-ryanp** [comment]
Should be fixed in https://github.com/doapp-ryanp/dynamodb-local/commit/1a3563b7932600ec8f2a5a645d56544acd138460

npmjs.com is giving me 500 errors so i cant update it in the regtistry ATM.

Once u see it bump to 0.0.11, please upgrade, re-test and close if it fixes.  Thanks

**Comment by charleswhchan** [comment]
@doapp-ryanp: Thanks for the update. 0.0.11 works! :+1: 

I will close the ticket.
